import type { Job, Company, Review, Application, Applicant, User, BlogPost } from './types';

export const DUMMY_COMPANIES: Company[] = [
  { id: '1', name: 'Innovate Inc.', logo: 'company-logo-1', industry: 'Tech', activeJobs: 5 },
  { id: '2', name: 'QuantumLeap', logo: 'company-logo-2', industry: 'AI', activeJobs: 3 },
  { id: '3', name: 'Synergy Corp', logo: 'company-logo-3', industry: 'Finance', activeJobs: 8 },
  { id: '4', name: 'PixelPerfect', logo: 'company-logo-4', industry: 'Design', activeJobs: 2 },
  { id: '5', name: 'DataDriven', logo: 'company-logo-5', industry: 'Analytics', activeJobs: 10 },
  { id: '6', name: 'HealthFirst', logo: 'company-logo-6', industry: 'Healthcare', activeJobs: 4 },
  { id: '7', name: 'Creative Studio', logo: 'company-logo-7', industry: 'Creative', activeJobs: 1 },
  { id: '8', name: 'Shopify Plus Experts', logo: 'company-logo-8', industry: 'E-commerce', activeJobs: 6 },
  { id: '9', name: 'Consulting Co', logo: 'company-logo-9', industry: 'Consulting', activeJobs: 7 },
  { id: '10', name: 'TravelNow', logo: 'company-logo-10', industry: 'Travel', activeJobs: 2 },
  { id: '11', name: 'FoodieFinds', logo: 'company-logo-11', industry: 'Food & Bev', activeJobs: 3 },
  { id: '12', name: 'Realty Group', logo: 'company-logo-12', industry: 'Real Estate', activeJobs: 5 },
];

export const DUMMY_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior React Developer',
    company: DUMMY_COMPANIES[0],
    description:
      'We are looking for a seasoned React developer to join our team. You will be responsible for building and maintaining our web applications.',
    location: 'San Francisco, CA',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: '$120k - $160k',
    postedDate: '2024-05-15',
    isUrgent: true,
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
  },
  {
    id: '2',
    title: 'Mid-level Next.js Developer',
    company: DUMMY_COMPANIES[1],
    description: 'Join our innovative team to work on exciting Next.js projects. Experience with Vercel is a plus.',
    location: 'Remote',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: '$90k - $110k',
    postedDate: '2024-05-14',
    isUrgent: false,
    skills: ['React', 'Next.js', 'TypeScript'],
  },
  {
    id: '3',
    title: 'Frontend Engineer (React)',
    company: DUMMY_COMPANIES[2],
    description:
      'Synergy Corp is hiring a frontend engineer to help build our next-generation financial platform.',
    location: 'New York, NY',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: '$110k - $130k',
    postedDate: '2024-05-12',
    isUrgent: false,
    skills: ['React', 'Redux', 'TypeScript', 'Jest'],
  },
  {
    id: '4',
    title: 'React Native Developer',
    company: DUMMY_COMPANIES[3],
    description: 'PixelPerfect is looking for a mobile developer with React Native expertise to create beautiful apps.',
    location: 'Los Angeles, CA',
    type: 'Contract',
    experienceLevel: 'Senior',
    salaryRange: '$100/hr',
    postedDate: '2024-05-10',
    isUrgent: true,
    skills: ['React Native', 'iOS', 'Android'],
  },
  {
    id: '5',
    title: 'Entry-level React Developer',
    company: DUMMY_COMPANIES[4],
    description: 'A great opportunity for a junior developer to grow their skills in a data-driven environment.',
    location: 'Chicago, IL',
    type: 'Full-time',
    experienceLevel: 'Entry',
    salaryRange: '$70k - $85k',
    postedDate: '2024-05-16',
    isUrgent: false,
    skills: ['React', 'JavaScript', 'CSS'],
  },
  {
    id: '6',
    title: 'Full-stack Engineer',
    company: DUMMY_COMPANIES[5],
    description:
      'HealthFirst needs a full-stack engineer with React and Node.js experience to improve our healthcare platform.',
    location: 'Boston, MA',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: '$100k - $125k',
    postedDate: '2024-05-13',
    isUrgent: false,
    skills: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
  },
  {
    id: '7',
    title: 'UI/UX Designer',
    company: DUMMY_COMPANIES[6],
    description: 'Creative Studio is looking for a talented UI/UX designer to create amazing user experiences.',
    location: 'Remote',
    type: 'Contract',
    experienceLevel: 'Mid-level',
    salaryRange: '$60/hr',
    postedDate: '2024-05-18',
    isUrgent: true,
    skills: ['Figma', 'Sketch', 'Adobe XD'],
  },
  {
    id: '8',
    title: 'Shopify Developer',
    company: DUMMY_COMPANIES[7],
    description: 'We are looking for a Shopify developer to build and maintain e-commerce websites.',
    location: 'Remote',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: '$95k - $115k',
    postedDate: '2024-05-17',
    isUrgent: false,
    skills: ['Shopify', 'Liquid', 'React', 'GraphQL'],
  },
  {
    id: '9',
    title: 'Senior Software Engineer',
    company: DUMMY_COMPANIES[8],
    description: 'Consulting Co is looking for a senior software engineer to lead client projects.',
    location: 'Washington D.C.',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: '$140k - $180k',
    postedDate: '2024-05-16',
    isUrgent: false,
    skills: ['Java', 'Python', 'AWS', 'React'],
  },
  {
    id: '10',
    title: 'Junior Frontend Developer',
    company: DUMMY_COMPANIES[9],
    description: 'Join our team as a junior frontend developer and work on exciting travel tech.',
    location: 'Austin, TX',
    type: 'Full-time',
    experienceLevel: 'Entry',
    salaryRange: '$75k - $90k',
    postedDate: '2024-05-15',
    isUrgent: false,
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
  },
  {
    id: '11',
    title: 'Backend Engineer',
    company: DUMMY_COMPANIES[10],
    description: 'FoodieFinds is looking for a backend engineer to build our food discovery platform.',
    location: 'Remote',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: '$100k - $130k',
    postedDate: '2024-05-14',
    isUrgent: false,
    skills: ['Node.js', 'Express', 'MongoDB'],
  },
  {
    id: '12',
    title: 'Real Estate Tech Lead',
    company: DUMMY_COMPANIES[11],
    description: 'Lead our engineering team to build the future of real estate technology.',
    location: 'Miami, FL',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: '$150k - $200k',
    postedDate: '2024-05-13',
    isUrgent: true,
    skills: ['React', 'Python', 'Django', 'GIS'],
  },
];

export const DUMMY_USERS = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com', avatar: 'avatar-1', role: 'Senior Developer' },
  { id: '2', name: 'Bob Williams', email: 'bob@example.com', avatar: 'avatar-2', role: 'Product Manager' },
  { id: '3', name: 'Charlie Brown', email: 'charlie@example.com', avatar: 'avatar-3', role: 'Designer' },
  { id: '4', name: 'Diana Prince', email: 'diana@example.com', avatar: 'avatar-4', role: 'Frontend Developer' },
  { id: '5', name: 'Ethan Hunt', email: 'ethan@example.com', avatar: 'avatar-5', role: 'Backend Developer' },
  { id: '6', name: 'Fiona Glenanne', email: 'fiona@example.com', avatar: 'avatar-6', role: 'UX Researcher' },
  { id: '7', name: 'George Costanza', email: 'george@example.com', avatar: 'avatar-7', role: 'Architect' },
  { id: '8', name: 'Heidi Turner', email: 'heidi@example.com', avatar: 'avatar-8', role: 'Data Scientist' },
  { id: '9', name: 'Ivan Petrov', email: 'ivan@example.com', avatar: 'avatar-9', role: 'DevOps Engineer' },
  { id: '10', name: 'Judy Hopps', email: 'judy@example.com', avatar: 'avatar-10', role: 'QA Engineer' },
  { id: '11', name: 'Kevin Malone', email: 'kevin@example.com', avatar: 'avatar-11', role: 'Accountant' },
  { id: '12', name: 'Linda Belcher', email: 'linda@example.com', avatar: 'avatar-12', role: 'Mobile Developer' },
];

export const DUMMY_REVIEWS: Review[] = [
  {
    id: '1',
    user: DUMMY_USERS[0],
    rating: 5,
    comment: 'ReactHire helped me find my dream job in just two weeks! The platform is intuitive and the recommendations were spot on.',
  },
  {
    id: '2',
    user: DUMMY_USERS[1],
    rating: 5,
    comment: 'As a hiring manager, ReactHire is my go-to. We found our new lead developer here and the process was seamless.',
  },
  {
    id: '3',
    user: DUMMY_USERS[3],
    rating: 4,
    comment: 'Great selection of jobs. The application tracker is a fantastic feature that kept me organized.',
  },
  {
    id: '4',
    user: DUMMY_USERS[6],
    rating: 5,
    comment: 'The quality of employers on this platform is top-notch. I received multiple offers.',
  },
  {
    id: '5',
    user: DUMMY_USERS[9],
    rating: 4,
    comment: 'A very user-friendly interface. It made my job search much less stressful.',
  },
];

export const DUMMY_APPLICATIONS: Application[] = [
  { id: '1', job: DUMMY_JOBS[0], user: DUMMY_USERS[0], status: 'Interview', appliedDate: '2024-05-10' },
  { id: '2', job: DUMMY_JOBS[1], user: DUMMY_USERS[0], status: 'Applied', appliedDate: '2024-05-15' },
  { id: '3', job: DUMMY_JOBS[2], user: DUMMY_USERS[0], status: 'Offer', appliedDate: '2024-05-01' },
  { id: '4', job: DUMMY_JOBS[3], user: DUMMY_USERS[0], status: 'Rejected', appliedDate: '2024-04-20' },
  { id: '5', job: DUMMY_JOBS[4], user: DUMMY_USERS[0], status: 'Hired', appliedDate: '2024-03-15' },
  { id: '6', job: DUMMY_JOBS[5], user: DUMMY_USERS[0], status: 'Screening', appliedDate: '2024-05-12' },
  { id: '7', job: DUMMY_JOBS[6], user: DUMMY_USERS[3], status: 'Applied', appliedDate: '2024-05-18' },
  { id: '8', job: DUMMY_JOBS[7], user: DUMMY_USERS[3], status: 'Interview', appliedDate: '2024-05-17' },
  { id: '9', job: DUMMY_JOBS[8], user: DUMMY_USERS[4], status: 'Applied', appliedDate: '2024-05-16' },
  { id: '10', job: DUMMY_JOBS[9], user: DUMMY_USERS[11], status: 'Screening', appliedDate: '2024-05-15' },
  { id: '11', job: DUMMY_JOBS[10], user: DUMMY_USERS[11], status: 'Rejected', appliedDate: '2024-05-14' },
  { id: '12', job: DUMMY_JOBS[11], user: DUMMY_USERS[0], status: 'Applied', appliedDate: '2024-05-19' },
];

export const DUMMY_APPLICANTS: Applicant[] = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com', avatar: 'avatar-1', jobId: '1', skillMatch: 95, experience: 5, status: 'Interview' },
  { id: '2', name: 'Diana Prince', email: 'diana@example.com', avatar: 'avatar-4', jobId: '1', skillMatch: 88, experience: 3, status: 'Shortlisted' },
  { id: '3', name: 'Ethan Hunt', email: 'ethan@example.com', avatar: 'avatar-5', jobId: '2', skillMatch: 82, experience: 7, status: 'Reviewed' },
  { id: '4', name: 'Frank Castle', email: 'frank@example.com', avatar: 'avatar-1', jobId: '3', skillMatch: 75, experience: 2, status: 'New' },
  { id: '5', name: 'Grace Hopper', email: 'grace@example.com', avatar: 'avatar-2', jobId: '4', skillMatch: 60, experience: 1, status: 'Rejected' },
  { id: '6', name: 'Fiona Glenanne', email: 'fiona@example.com', avatar: 'avatar-6', jobId: '1', skillMatch: 92, experience: 6, status: 'Interview' },
  { id: '7', name: 'George Costanza', email: 'george@example.com', avatar: 'avatar-7', jobId: '5', skillMatch: 78, experience: 10, status: 'New' },
  { id: '8', name: 'Heidi Turner', email: 'heidi@example.com', avatar: 'avatar-8', jobId: '6', skillMatch: 85, experience: 4, status: 'Shortlisted' },
  { id: '9', name: 'Ivan Petrov', email: 'ivan@example.com', avatar: 'avatar-9', jobId: '2', skillMatch: 90, experience: 5, status: 'Hired' },
  { id: '10', name: 'Judy Hopps', email: 'judy@example.com', avatar: 'avatar-10', jobId: '8', skillMatch: 70, experience: 2, status: 'Reviewed' },
  { id: '11', name: 'Kevin Malone', email: 'kevin@example.com', avatar: 'avatar-11', jobId: '9', skillMatch: 65, experience: 8, status: 'Rejected' },
  { id: '12', name: 'Linda Belcher', email: 'linda@example.com', avatar: 'avatar-12', jobId: '11', skillMatch: 98, experience: 3, status: 'Hired' },
];

export const DUMMY_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    slug: 'how-to-ace-your-next-react-interview',
    title: 'How to Ace Your Next React Interview',
    author: DUMMY_USERS[0],
    date: '2024-05-20',
    image: 'blog-post-1',
    excerpt: 'Our comprehensive guide to help you prepare for and ace your next React developer interview. From core concepts to advanced topics, we have got you covered.',
    content: '<p>Lorem ipsum...</p>',
  },
  {
    id: '2',
    slug: 'top-5-trends-in-web-development-for-2024',
    title: 'Top 5 Trends in Web Development for 2024',
    author: DUMMY_USERS[1],
    date: '2024-05-18',
    image: 'blog-post-2',
    excerpt: 'Stay ahead of the curve. We explore the top 5 trends shaping the future of web development, from AI integration to serverless architectures.',
    content: '<p>Lorem ipsum...</p>',
  },
  {
    id: '3',
    slug: 'crafting-the-perfect-developer-resume',
    title: 'Crafting the Perfect Developer Resume',
    author: DUMMY_USERS[2],
    date: '2024-05-15',
    image: 'blog-post-3',
    excerpt: 'Your resume is your first impression. Learn how to craft a compelling developer resume that stands out to recruiters and hiring managers.',
    content: '<p>Lorem ipsum...</p>',
  }
];
