import type { Job, Company, Review, Application, Applicant, User, BlogPost } from './types';
import { Briefcase, Code, Headset, Megaphone, PenTool, Search, Users, BookOpen, Palette, Wallet, BrainCircuit, GitMerge, KanbanSquare, Scale, Stethoscope, Clapperboard } from 'lucide-react';
import type { LucideProps } from 'lucide-react';
import React from 'react';

export const DUMMY_COMPANIES: Company[] = [
  { id: '1', name: 'Innovate Inc.', logo: 'company-logo-1', industry: 'Tech', activeJobs: 5, rating: 5, location: 'Accra, Ghana' },
  { id: '2', name: 'QuantumLeap', logo: 'company-logo-2', industry: 'AI', activeJobs: 3, rating: 4, location: 'Accra, Ghana' },
  { id: '3', name: 'Synergy Corp', logo: 'company-logo-3', industry: 'Finance', activeJobs: 8, rating: 5, location: 'Accra, Ghana' },
  { id: '4', name: 'PixelPerfect', logo: 'company-logo-4', industry: 'Design', activeJobs: 2, rating: 4, location: 'Accra, Ghana' },
  { id: '5', name: 'DataDriven', logo: 'company-logo-5', industry: 'Analytics', activeJobs: 10, rating: 5, location: 'Accra, Ghana' },
  { id: '6', name: 'HealthFirst', logo: 'company-logo-6', industry: 'Healthcare', activeJobs: 4, rating: 3, location: 'Takoradi, Ghana' },
  { id: '7', name: 'Creative Studio', logo: 'company-logo-7', industry: 'Creative', activeJobs: 1, rating: 5, location: 'Remote' },
  { id: '8', name: 'Shopify Plus Experts', logo: 'company-logo-8', industry: 'E-commerce', activeJobs: 6, rating: 5, location: 'Remote' },
  { id: '9', name: 'Consulting Co', logo: 'company-logo-9', industry: 'Consulting', activeJobs: 7, rating: 4, location: 'Accra, Ghana' },
  { id: '10', name: 'TravelNow', logo: 'company-logo-10', industry: 'Travel', activeJobs: 2, rating: 3, location: 'Cape Coast, Ghana' },
  { id: '11', name: 'FoodieFinds', logo: 'company-logo-11', industry: 'Food & Bev', activeJobs: 3, rating: 4, location: 'Tema, Ghana' },
  { id: '12', name: 'Realty Group', logo: 'company-logo-12', industry: 'Real Estate', activeJobs: 5, rating: 5, location: 'Kumasi, Ghana' },
  { id: '13', name: 'Apex Solutions', logo: 'company-logo-13', industry: 'IT Services', activeJobs: 4, rating: 4, location: 'Accra, Ghana' },
  { id: '14', name: 'Zenith Media', logo: 'company-logo-14', industry: 'Marketing', activeJobs: 2, rating: 5, location: 'Remote' },
  { id: '15', name: 'Momentum Dynamics', logo: 'company-logo-15', industry: 'Automotive', activeJobs: 6, rating: 4, location: 'Tema, Ghana' },
  { id: '16', name: 'Starlight Studios', logo: 'company-logo-16', industry: 'Entertainment', activeJobs: 3, rating: 5, location: 'Accra, Ghana' },
  { id: '17', name: 'Terra Firma', logo: 'company-logo-17', industry: 'Agriculture', activeJobs: 5, rating: 3, location: 'Tamale, Ghana' },
  { id: '18', name: 'Catalyst Ventures', logo: 'company-logo-18', industry: 'Venture Capital', activeJobs: 1, rating: 5, location: 'Accra, Ghana' },
  { id: '19', name: 'Infinity Loop', logo: 'company-logo-19', industry: 'Software', activeJobs: 8, rating: 4, location: 'Accra, Ghana' },
  { id: '20', name: 'Blue Ocean Robotics', logo: 'company-logo-20', industry: 'Robotics', activeJobs: 4, rating: 5, location: 'Takoradi, Ghana' },
  { id: '21', name: 'Pinnacle Arch', logo: 'company-logo-21', industry: 'Architecture', activeJobs: 2, rating: 4, location: 'Accra, Ghana' },
  { id: '22', name: 'Nomad Goods', logo: 'company-logo-22', industry: 'Retail', activeJobs: 7, rating: 5, location: 'Accra, Ghana' },
  { id: '23', name: 'Evergreen Financial', logo: 'company-logo-23', industry: 'Finance', activeJobs: 3, rating: 4, location: 'Tema, Ghana' },
  { id: '24', name: 'Odyssey Travel', logo: 'company-logo-24', industry: 'Travel', activeJobs: 5, rating: 5, location: 'Remote' },
];

export const DUMMY_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior React Developer',
    company: DUMMY_COMPANIES[0],
    description:
      'We are looking for a seasoned React developer to join our team. You will be responsible for building and maintaining our web applications.',
    location: 'Accra, Ghana',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: 'GH₵120k - GH₵160k',
    postedDate: '2024-05-10',
    isUrgent: true,
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    category: 'Software',
  },
  {
    id: '2',
    title: 'Mid-level Next.js Developer',
    company: DUMMY_COMPANIES[1],
    description: 'Join our innovative team to work on exciting Next.js projects. Experience with Vercel is a plus.',
    location: 'Remote',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵90k - GH₵110k',
    postedDate: '2024-05-11',
    isUrgent: false,
    skills: ['React', 'Next.js', 'TypeScript'],
    category: 'Software',
  },
  {
    id: '3',
    title: 'Frontend Engineer (React)',
    company: DUMMY_COMPANIES[2],
    description:
      'Synergy Corp is hiring a frontend engineer to help build our next-generation financial platform.',
    location: 'Accra, Ghana',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵110k - GH₵130k',
    postedDate: '2024-05-12',
    isUrgent: false,
    skills: ['React', 'Redux', 'TypeScript', 'Jest'],
    category: 'Software',
  },
  {
    id: '4',
    title: 'React Native Developer',
    company: DUMMY_COMPANIES[3],
    description: 'PixelPerfect is looking for a mobile developer with React Native expertise to create beautiful apps.',
    location: 'Kumasi, Ghana',
    type: 'Contract',
    experienceLevel: 'Senior',
    salaryRange: 'GH₵100 /hr',
    postedDate: '2024-05-13',
    isUrgent: true,
    skills: ['React Native', 'iOS', 'Android'],
    category: 'Software',
  },
  {
    id: '5',
    title: 'Entry-level React Developer',
    company: DUMMY_COMPANIES[4],
    description: 'A great opportunity for a junior developer to grow their skills in a data-driven environment.',
    location: 'Tema, Ghana',
    type: 'Full-time',
    experienceLevel: 'Entry',
    salaryRange: 'GH₵70k - GH₵85k',
    postedDate: '2024-05-18',
    isUrgent: false,
    skills: ['React', 'JavaScript', 'CSS'],
    category: 'Software',
  },
  {
    id: '6',
    title: 'Full-stack Engineer',
    company: DUMMY_COMPANIES[5],
    description:
      'HealthFirst needs a full-stack engineer with React and Node.js experience to improve our healthcare platform.',
    location: 'Takoradi, Ghana',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵100k - GH₵125k',
    postedDate: '2024-05-17',
    isUrgent: false,
    skills: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    category: 'Healthcare',
  },
  {
    id: '7',
    title: 'UI/UX Designer',
    company: DUMMY_COMPANIES[6],
    description: 'Creative Studio is looking for a talented UI/UX designer to create amazing user experiences.',
    location: 'Remote',
    type: 'Contract',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵60 /hr',
    postedDate: '2024-05-19',
    isUrgent: true,
    skills: ['Figma', 'Sketch', 'Adobe XD'],
    category: 'Design',
  },
  {
    id: '8',
    title: 'Shopify Developer',
    company: DUMMY_COMPANIES[7],
    description: 'We are looking for a Shopify developer to build and maintain e-commerce websites.',
    location: 'Remote',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵95k - GH₵115k',
    postedDate: '2024-05-15',
    isUrgent: false,
    skills: ['Shopify', 'Liquid', 'React', 'GraphQL'],
    category: 'Software',
  },
  {
    id: '9',
    title: 'Senior Software Engineer',
    company: DUMMY_COMPANIES[8],
    description: 'Consulting Co is looking for a senior software engineer to lead client projects.',
    location: 'Accra, Ghana',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: 'GH₵140k - GH₵180k',
    postedDate: '2024-05-16',
    isUrgent: false,
    skills: ['Java', 'Python', 'AWS', 'React'],
    category: 'Software',
  },
  {
    id: '10',
    title: 'Junior Frontend Developer',
    company: DUMMY_COMPANIES[9],
    description: 'Join our team as a junior frontend developer and work on exciting travel tech.',
    location: 'Accra, Ghana',
    type: 'Full-time',
    experienceLevel: 'Entry',
    salaryRange: 'GH₵75k - GH₵90k',
    postedDate: '2024-05-15',
    isUrgent: false,
    skills: ['HTML', 'CSS', 'JavaScript', 'React'],
    category: 'Software',
  },
  {
    id: '11',
    title: 'Backend Engineer',
    company: DUMMY_COMPANIES[10],
    description: 'FoodieFinds is looking for a backend engineer to build our food discovery platform.',
    location: 'Remote',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵100k - GH₵130k',
    postedDate: '2024-05-14',
    isUrgent: false,
    skills: ['Node.js', 'Express', 'MongoDB'],
    category: 'Software',
  },
  {
    id: '12',
    title: 'Real Estate Tech Lead',
    company: DUMMY_COMPANIES[11],
    description: 'Lead our engineering team to build the future of real estate technology.',
    location: 'Cape Coast, Ghana',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: 'GH₵150k - GH₵200k',
    postedDate: '2024-05-13',
    isUrgent: true,
    skills: ['React', 'Python', 'Django', 'GIS'],
    category: 'Management',
  },
   {
    id: '13',
    title: 'Cloud Solutions Architect',
    company: DUMMY_COMPANIES[12],
    description: 'Design and implement cloud infrastructure for our enterprise clients.',
    location: 'Accra, Ghana',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: 'GH₵160k - GH₵190k',
    postedDate: '2024-05-19',
    isUrgent: false,
    skills: ['AWS', 'Azure', 'GCP', 'Terraform'],
    category: 'DevOps',
  },
  {
    id: '14',
    title: 'Digital Marketing Manager',
    company: DUMMY_COMPANIES[13],
    description: 'Lead our digital marketing campaigns and grow our online presence.',
    location: 'Remote',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵80k - GH₵100k',
    postedDate: '2024-05-18',
    isUrgent: false,
    skills: ['SEO', 'SEM', 'Google Analytics', 'Content Marketing'],
    category: 'Marketing & Sale',
  },
  {
    id: '15',
    title: 'Automotive Embedded Engineer',
    company: DUMMY_COMPANIES[14],
    description: 'Develop embedded software for next-generation vehicle control units.',
    location: 'Tema, Ghana',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵110k - GH₵140k',
    postedDate: '2024-05-17',
    isUrgent: true,
    skills: ['C++', 'Embedded C', 'CAN', 'AUTOSAR'],
    category: 'Software',
  },
  {
    id: '16',
    title: 'Game Developer (Unity)',
    company: DUMMY_COMPANIES[15],
    description: 'Join our studio to create immersive and exciting mobile games.',
    location: 'Kumasi, Ghana',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵90k - GH₵120k',
    postedDate: '2024-05-16',
    isUrgent: false,
    skills: ['Unity', 'C#', '3D Modeling'],
    category: 'Software',
  },
  {
    id: '17',
    title: 'Agricultural Tech Specialist',
    company: DUMMY_COMPANIES[16],
    description: 'Implement and support precision agriculture technologies on large-scale farms.',
    location: 'Tamale, Ghana',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵85k - GH₵105k',
    postedDate: '2024-05-15',
    isUrgent: false,
    skills: ['Agronomy', 'GPS', 'Drones', 'Data Analysis'],
    category: 'Data Science',
  },
  {
    id: '18',
    title: 'Venture Capital Analyst',
    company: DUMMY_COMPANIES[17],
    description: 'Identify and analyze investment opportunities in early-stage tech startups.',
    location: 'Accra, Ghana',
    type: 'Full-time',
    experienceLevel: 'Entry',
    salaryRange: 'GH₵100k+ /year',
    postedDate: '2024-05-14',
    isUrgent: true,
    skills: ['Financial Modeling', 'Due Diligence', 'Market Research'],
    category: 'Finance',
  },
  {
    id: '19',
    title: 'Senior iOS Developer',
    company: DUMMY_COMPANIES[18],
    description: 'Lead the development of our flagship iOS application.',
    location: 'Accra, Ghana',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: 'GH₵170k - GH₵210k',
    postedDate: '2024-05-13',
    isUrgent: false,
    skills: ['Swift', 'Objective-C', 'Xcode', 'CoreData'],
    category: 'Software',
  },
  {
    id: '20',
    title: 'Robotics Software Engineer',
    company: DUMMY_COMPANIES[19],
    description: 'Develop software for autonomous mobile robots.',
    location: 'Takoradi, Ghana',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵120k - GH₵150k',
    postedDate: '2024-05-12',
    isUrgent: false,
    skills: ['ROS', 'C++', 'Python', 'SLAM'],
    category: 'Software',
  },
  {
    id: '21',
    title: 'Architectural Designer',
    company: DUMMY_COMPANIES[20],
    description: 'Create innovative and sustainable designs for commercial and residential projects.',
    location: 'Accra, Ghana',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵80k - GH₵100k',
    postedDate: '2024-05-11',
    isUrgent: false,
    skills: ['AutoCAD', 'Revit', 'SketchUp', 'BIM'],
    category: 'Design',
  },
  {
    id: '22',
    title: 'Retail Store Manager',
    company: DUMMY_COMPANIES[21],
    description: 'Manage daily operations and lead a team to success in our flagship store.',
    location: 'Kumasi, Ghana',
    type: 'Full-time',
    experienceLevel: 'Senior',
    salaryRange: 'GH₵70k - GH₵90k',
    postedDate: '2024-05-10',
    isUrgent: false,
    skills: ['Retail Management', 'Sales', 'Customer Service', 'Inventory Control'],
    category: 'Management',
  },
  {
    id: '23',
    title: 'Financial Advisor',
    company: DUMMY_COMPANIES[22],
    description: 'Provide comprehensive financial planning and investment advice to clients.',
    location: 'Tema, Ghana',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵90k+ /year',
    postedDate: '2024-05-09',
    isUrgent: false,
    skills: ['CFP', 'Series 7', 'Investment Management', 'Retirement Planning'],
    category: 'Finance',
  },
  {
    id: '24',
    title: 'Travel Consultant',
    company: DUMMY_COMPANIES[23],
    description: 'Curate and book luxury travel experiences for high-end clientele.',
    location: 'Remote',
    type: 'Full-time',
    experienceLevel: 'Mid-level',
    salaryRange: 'GH₵60k - GH₵80k',
    postedDate: '2024-05-08',
    isUrgent: false,
    skills: ['Luxury Travel', 'Sales', 'GDS', 'Customer Service'],
    category: 'Customer Help',
  },
];

export const DUMMY_USERS: User[] = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com', avatar: 'avatar-1', role: 'Senior Developer' },
  { id: '2', name: 'Bob Williams', email: 'bob@example.com', avatar: 'avatar-2', role: 'Product Manager' },
  { id: '3', name: 'Charlie Brown', email: 'charlie@example.com', avatar: 'avatar-3', role: 'Designer' },
  { id: '4', name: 'Diana Prince', email: 'diana@example.com', avatar: 'avatar-4', role: 'Frontend Developer' },
  { id: '5', name: 'Ethan Hunt', email: 'ethan@example.com', avatar: 'avatar-5', role: 'Backend Developer' },
  { id: '6', name: 'Fiona Glenanne', email: 'fiona@example.com', avatar: 'avatar-6', role: 'UX Researcher' },
  { id: '7', name: 'George Costanza', email: 'george@example.com', avatar: 'avatar-7', role: 'Architect' },
  { id: '8', name: 'Heidi Turner', email: 'heidi@example.com', avatar: 'avatar-8', role: 'Data Scientist' },
  { id: '9', name: 'Ivan Petrov', email: 'ivan@example.com', avatar: 'avatar-9', role: 'DevOps Engineer' },
  { id: '10', name: 'Judy Hopps', email: 'judy@example.com', avatar: 'avatar-10', role: 'QA Engineer' },
  { id: '11', name: 'Kevin Malone', email: 'kevin@example.com', avatar: 'avatar-11', role: 'Accountant' },
  { id: '12', name: 'Linda Belcher', email: 'linda@example.com', avatar: 'avatar-12', role: 'Mobile Developer' },
  { id: '13', name: 'Michael Scott', email: 'michael@example.com', avatar: 'avatar-13', role: 'Regional Manager' },
  { id: '14', name: 'Nancy Drew', email: 'nancy@example.com', avatar: 'avatar-14', role: 'Detective' },
  { id: '15', name: 'Oliver Twist', email: 'oliver@example.com', avatar: 'avatar-15', role: 'Orphan' },
  { id: '16', name: 'Peter Pan', email: 'peter@example.com', avatar: 'avatar-16', role: 'Lost Boy' },
  { id: '17', name: 'Quinn Fabray', email: 'quinn@example.com', avatar: 'avatar-17', role: 'Cheerleader' },
  { id: '18', name: 'Rachel Green', email: 'rachel@example.com', avatar: 'avatar-18', role: 'Fashion Executive' },
  { id: '19', name: 'Steve Rogers', email: 'steve@example.com', avatar: 'avatar-19', role: 'Avenger' },
  { id: '20', name: 'Tony Stark', email: 'tony@example.com', avatar: 'avatar-20', role: 'CEO' },
  { id: '21', name: 'Ursula Buffay', email: 'ursula@example.com', avatar: 'avatar-21', role: 'Masseuse' },
  { id: '22', name: 'Vito Corleone', email: 'vito@example.com', avatar: 'avatar-22', role: 'Godfather' },
  { id: '23', name: 'Walter White', email: 'walter@example.com', avatar: 'avatar-23', role: 'Chemist' },
  { id: '24', name: 'Xena Warrior', email: 'xena@example.com', avatar: 'avatar-24', role: 'Princess' },
];

export const DUMMY_REVIEWS: Review[] = [
  {
    id: '1',
    user: DUMMY_USERS[0],
    rating: 5,
    comment: 'JobBox helped me find my dream job in just two weeks! The platform is intuitive and the recommendations were spot on.',
  },
  {
    id: '2',
    user: DUMMY_USERS[1],
    rating: 5,
    comment: 'As a hiring manager, JobBox is my go-to. We found our new lead developer here and the process was seamless.',
  },
  {
    id: '3',
    user: DUMMY_USERS[3],
    rating: 4,
    comment: 'Great selection of jobs. The application tracker is a fantastic feature that kept me organized.',
  },
  {
    id: '4',
    user: DUMMY_USERS[6],
    rating: 5,
    comment: 'The quality of employers on this platform is top-notch. I received multiple offers.',
  },
  {
    id: '5',
    user: DUMMY_USERS[9],
    rating: 4,
    comment: 'A very user-friendly interface. It made my job search much less stressful.',
  },
  {
    id: '6',
    user: DUMMY_USERS[12],
    rating: 5,
    comment: 'The AI recommendations were surprisingly accurate. Found a perfect fit for my skills.',
  },
  {
    id: '7',
    user: DUMMY_USERS[15],
    rating: 4,
    comment: 'I appreciate the focus on React-specific jobs. It cuts through the noise of generic job boards.',
  },
  {
    id: '8',
    user: DUMMY_USERS[18],
    rating: 5,
    comment: 'The entire process from application to offer was smooth. Highly recommend JobBox!',
  },
];

export const DUMMY_APPLICATIONS: Application[] = [
  { id: '1', job: DUMMY_JOBS[0], user: DUMMY_USERS[0], status: 'Interview', appliedDate: '2024-05-10' },
  { id: '2', job: DUMMY_JOBS[1], user: DUMMY_USERS[0], status: 'Applied', appliedDate: '2024-05-15' },
  { id: '3', job: DUMMY_JOBS[2], user: DUMMY_USERS[0], status: 'Offer', appliedDate: '2024-05-01' },
  { id: '4', job: DUMMY_JOBS[3], user: DUMMY_USERS[0], status: 'Rejected', appliedDate: '2024-04-20' },
  { id: '5', job: DUMMY_JOBS[4], user: DUMMY_USERS[0], status: 'Hired', appliedDate: '2024-03-15' },
  { id: '6', job: DUMMY_JOBS[5], user: DUMMY_USERS[0], status: 'Screening', appliedDate: '2024-05-12' },
  { id: '7', job: DUMMY_JOBS[6], user: DUMMY_USERS[3], status: 'Applied', appliedDate: '2024-05-18' },
  { id: '8', job: DUMMY_JOBS[7], user: DUMMY_USERS[3], status: 'Interview', appliedDate: '2024-05-17' },
  { id: '9', job: DUMMY_JOBS[8], user: DUMMY_USERS[4], status: 'Applied', appliedDate: '2024-05-16' },
  { id: '10', job: DUMMY_JOBS[9], user: DUMMY_USERS[11], status: 'Screening', appliedDate: '2024-05-15' },
  { id: '11', job: DUMMY_JOBS[10], user: DUMMY_USERS[11], status: 'Rejected', appliedDate: '2024-05-14' },
  { id: '12', job: DUMMY_JOBS[11], user: DUMMY_USERS[0], status: 'Applied', appliedDate: '2024-05-19' },
];

export const DUMMY_APPLICANTS: Applicant[] = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com', avatar: 'avatar-1', jobId: '1', skillMatch: 95, experience: 5, status: 'Interview' },
  { id: '2', name: 'Diana Prince', email: 'diana@example.com', avatar: 'avatar-4', jobId: '1', skillMatch: 88, experience: 3, status: 'Shortlisted' },
  { id: '3', name: 'Ethan Hunt', email: 'ethan@example.com', avatar: 'avatar-5', jobId: '2', skillMatch: 82, experience: 7, status: 'Reviewed' },
  { id: '4', name: 'Frank Castle', email: 'frank@example.com', avatar: 'avatar-1', jobId: '3', skillMatch: 75, experience: 2, status: 'New' },
  { id: '5', name: 'Grace Hopper', email: 'grace@example.com', avatar: 'avatar-2', jobId: '4', skillMatch: 60, experience: 1, status: 'Rejected' },
  { id: '6', name: 'Fiona Glenanne', email: 'fiona@example.com', avatar: 'avatar-6', jobId: '1', skillMatch: 92, experience: 6, status: 'Interview' },
  { id: '7', name: 'George Costanza', email: 'george@example.com', avatar: 'avatar-7', jobId: '5', skillMatch: 78, experience: 10, status: 'New' },
  { id: '8', name: 'Heidi Turner', email: 'heidi@example.com', avatar: 'avatar-8', jobId: '6', skillMatch: 85, experience: 4, status: 'Shortlisted' },
  { id: '9', name: 'Ivan Petrov', email: 'ivan@example.com', avatar: 'avatar-9', jobId: '2', skillMatch: 90, experience: 5, status: 'Hired' },
  { id: '10', name: 'Judy Hopps', email: 'judy@example.com', avatar: 'avatar-10', jobId: '8', skillMatch: 70, experience: 2, status: 'Reviewed' },
  { id: '11', name: 'Kevin Malone', email: 'kevin@example.com', avatar: 'avatar-11', jobId: '9', skillMatch: 65, experience: 8, status: 'Rejected' },
  { id: '12', name: 'Linda Belcher', email: 'linda@example.com', avatar: 'avatar-12', jobId: '11', skillMatch: 98, experience: 3, status: 'Hired' },
];

export const DUMMY_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    slug: 'how-to-ace-your-next-react-interview',
    title: 'How to Ace Your Next React Interview',
    author: DUMMY_USERS[0],
    date: '2024-05-20',
    image: 'blog-post-1',
    excerpt: 'Our comprehensive guide to help you prepare for and ace your next React developer interview. From core concepts to advanced topics, we have got you covered.',
    content: '<p>Lorem ipsum...</p>',
  },
  {
    id: '2',
    slug: 'top-5-trends-in-web-development-for-2024',
    title: 'Top 5 Trends in Web Development for 2024',
    author: DUMMY_USERS[1],
    date: '2024-05-18',
    image: 'blog-post-2',
    excerpt: 'Stay ahead of the curve. We explore the top 5 trends shaping the future of web development, from AI integration to serverless architectures.',
    content: '<p>Lorem ipsum...</p>',
  },
  {
    id: '3',
    slug: 'crafting-the-perfect-developer-resume',
    title: 'Crafting the Perfect Developer Resume',
    author: DUMMY_USERS[2],
    date: '2024-05-15',
    image: 'blog-post-3',
    excerpt: 'Your resume is your first impression. Learn how to craft a compelling developer resume that stands out to recruiters and hiring managers.',
    content: '<p>Lorem ipsum...</p>',
  },
  {
    id: '4',
    slug: 'the-rise-of-serverless-react',
    title: 'The Rise of Serverless React',
    author: DUMMY_USERS[12],
    date: '2024-05-12',
    image: 'blog-post-4',
    excerpt: 'Explore how serverless architectures are changing the game for React developers, enabling scalable and cost-effective applications.',
    content: '<p>Lorem ipsum...</p>',
  },
  {
    id: '5',
    slug: 'a-guide-to-state-management-in-next-js',
    title: 'A Guide to State Management in Next.js',
    author: DUMMY_USERS[13],
    date: '2024-05-10',
    image: 'blog-post-5',
    excerpt: 'From simple useState to complex solutions like Redux and Zustand, we cover the best ways to manage state in your Next.js applications.',
    content: '<p>Lorem ipsum...</p>',
  },
  {
    id: '6',
    slug: 'remote-work-best-practices-for-developers',
    title: 'Remote Work Best Practices for Developers',
    author: DUMMY_USERS[14],
    date: '2024-05-08',
    image: 'blog-post-6',
    excerpt: 'Maximize your productivity and maintain a healthy work-life balance with these essential tips for remote software developers.',
    content: '<p>Lorem ipsum...</p>',
  },
];

export const JOB_CATEGORIES = [
    { name: 'Content Writer', jobCount: '29 Jobs', icon: PenTool, color: 'text-sky-800', iconBgColor: 'bg-sky-100' },
    { name: 'Market Research', jobCount: '7 Jobs', icon: Search, color: 'text-violet-800', iconBgColor: 'bg-violet-100' },
    { name: 'Marketing & Sale', jobCount: '9 Jobs', icon: Megaphone, color: 'text-amber-800', iconBgColor: 'bg-amber-100' },
    { name: 'Customer Help', jobCount: '4 Jobs', icon: Headset, color: 'text-rose-800', iconBgColor: 'bg-rose-100' },
    { name: 'Finance', jobCount: '9 Jobs', icon: Wallet, color: 'text-emerald-800', iconBgColor: 'bg-emerald-100' },
    { name: 'Software', jobCount: '4 Jobs', icon: Code, color: 'text-cyan-800', iconBgColor: 'bg-cyan-100' },
    { name: 'Human Resource', jobCount: '10 Jobs', icon: Users, color: 'text-fuchsia-800', iconBgColor: 'bg-fuchsia-100' },
    { name: 'Management', jobCount: '6 Jobs', icon: Briefcase, color: 'text-indigo-800', iconBgColor: 'bg-indigo-100' },
    { name: 'Design', jobCount: '5 Jobs', icon: Palette, color: 'text-pink-800', iconBgColor: 'bg-pink-100' },
    { name: 'Education', jobCount: '12 Jobs', icon: BookOpen, color: 'text-orange-800', iconBgColor: 'bg-orange-100' },
    { name: 'Data Science', jobCount: '8 Jobs', icon: BrainCircuit, color: 'text-blue-800', iconBgColor: 'bg-blue-100' },
    { name: 'DevOps', jobCount: '5 Jobs', icon: GitMerge, color: 'text-teal-800', iconBgColor: 'bg-teal-100' },
    { name: 'Product Management', jobCount: '7 Jobs', icon: KanbanSquare, color: 'text-purple-800', iconBgColor: 'bg-purple-100' },
    { name: 'Legal', jobCount: '3 Jobs', icon: Scale, color: 'text-gray-800', iconBgColor: 'bg-gray-100' },
    { name: 'Healthcare', jobCount: '11 Jobs', icon: Stethoscope, color: 'text-red-800', iconBgColor: 'bg-red-100' },
    { name: 'Media', jobCount: '6 Jobs', icon: Clapperboard, color: 'text-yellow-800', iconBgColor: 'bg-yellow-100' },
  ];

export const DUMMY_LOCATIONS = [
    { name: 'Accra, Ghana', jobs: 12, companies: 8, imageId: 'location-accra' },
    { name: 'Kumasi, Ghana', jobs: 8, companies: 5, imageId: 'location-kumasi' },
    { name: 'Takoradi, Ghana', jobs: 5, companies: 3, imageId: 'location-takoradi' },
    { name: 'Cape Coast, Ghana', jobs: 3, companies: 2, imageId: 'location-cape-coast' },
    { name: 'Tamale, Ghana', jobs: 4, companies: 3, imageId: 'location-tamale' },
    { name: 'Tema, Ghana', jobs: 6, companies: 4, imageId: 'location-tema' },
  ];
